server:
  port: 8082

spring:
  application:
    name: ms-email
  datasource:
    password: shopms
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: DATA_MAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: rbalconi.dev@gmail.com
    password: XXXXXXXXXXXXXXXXXXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

